// Dubai main areas for real estate (sorted by popularity)
export const DUBAI_AREAS = [
  // Most popular areas
  "Dubai Marina",
  "Downtown Dubai",
  "Palm Jumeirah",
  "Business Bay",
  "JBR (Jumeirah Beach Residence)",
  "Dubai Hills",
  "Arabian Ranches",
  "JLT (Jumeirah Lakes Towers)",
  "DIFC (Dubai International Financial Centre)",
  "Jumeirah",
  "Dubai Creek Harbour",
  "Dubai Festival City",
  "Emirates Hills",
  "The Springs",
  "The Meadows",
  "The Lakes",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Al Barsha",
  "Dubai Sports City",
  "Dubai Silicon Oasis",
  "The Greens",
  "The Views",
  "Discovery Gardens",
  "International City",
  "Dubai Healthcare City",
  "Dubai Motor City",
  "Dubai Production City (IMPZ)",
  "Dubai Media City",
  "Dubai Internet City",
  "Dubai Knowledge Park",
  "Dubai Investment Park",
  "Al Sufouh",
  "Umm Suqeim",
  "Deira",
  "Bur Dubai",
  "Mirdif",
] as const
