// Dubai areas for real estate
export const DUBAI_AREAS = [
  "Dubai Marina",
  "JBR (Jumeirah Beach Residence)",
  "Downtown Dubai",
  "Business Bay",
  "Palm Jumeirah",
  "Dubai Hills",
  "Arabian Ranches",
  "JLT (Jumeirah Lakes Towers)",
  "DIFC (Dubai International Financial Centre)",
  "Dubai Sports City",
  "Dubai Silicon Oasis",
  "Dubai Production City (IMPZ)",
  "Dubai Media City",
  "Dubai Internet City",
  "Dubai Knowledge Park",
  "Al Barsha",
  "Al Sufouh",
  "Jumeirah",
  "Umm Suqeim",
  "Al Wasl",
  "Al Safa",
  "Al Quoz",
  "Al Karama",
  "Bur Dubai",
  "Deira",
  "Al Rigga",
  "Al Muraqqabat",
  "Al Muteena",
  "Al Ras",
  "Al Buteen",
  "Al Nahda",
  "Al Qusais",
  "Mirdif",
  "Muhaisnah",
  "Al Rashidiya",
  "Al Mizhar",
  "Al Twar",
  "Al Khawaneej",
  "Mushrif",
  "Al Garhoud",
  "Dubai Creek Harbour",
  "Dubai Festival City",
  "Dubai Healthcare City",
  "Dubai Motor City",
  "Dubai Studio City",
  "Dubai Science Park",
  "Dubai International Academic City",
  "Dubai Investment Park",
  "Dubai World Central",
  "Jumeirah Village Circle (JVC)",
  "Jumeirah Village Triangle (JVT)",
  "Emirates Hills",
  "The Springs",
  "The Meadows",
  "The Lakes",
  "The Greens",
  "The Views",
  "Discovery Gardens",
  "International City",
] as const
